version: '3.8'

services:
  #php apache
  php-apache:
    build:
      ./config/php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/src
    restart:
      always
    depends_on:
      - mysql

  # mysql
  mysql:
    build:
      ./config/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./config/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    restart:
      always
